# Generated by scripts/sync_large_text_product_rules.py; do not edit.
from __future__ import annotations
import json
import re
from decimal import Decimal, InvalidOperation
from typing import Any
from .punctuation_policy import punctuation_issues
from .quantity_guard import quantity_issues, visible_text, WORDS
from .semantic_constraints import semantic_constraint_issues


TOKEN_RE = re.compile(r"\\n|<@\d+>|\{[^{}\s]+\}|%[sdif]|##\d+|#[A-Za-z]\d*#|</?[A-Za-z][^>\s]*[^>]*>|\[[A-Za-z0-9_:/#=.,-]+\]")


CJK_RE = re.compile(r"[\u3400-\u9fff]")


MOJIBAKE_RE = re.compile(r"\ufffd|\x00|\?{3}")


NUMBER_RE = re.compile(
    # 拉丁扩展及组合重音仍是词的一部分，不能把 Bäume/Mũ 的首字母识别为单位。
    r"\d+(?:[,.]\d+)?(?:\s*(?:千|万|萬|亿|億|(?i:thousand|million|billion|ribu|rb|juta|miliar|millones|millón|milhao|milhão|milhões|mil|тыс|тысяч|тысяча|тысячи|млн|миллион|миллиона|миллионов|млрд|миллиард|миллиарда|миллиардов)\b\.?|[KkMBWw](?![A-Za-z\u00c0-\u024f\u1e00-\u1eff\u0300-\u036f])))%?"
    r"|\d{1,3}(?:[,. \u00a0\u202f]\d{3})+(?:[,.]\d+)?%?"
    r"|\d+(?:[,.]\d+)?%?"
)


WORD_MULTIPLIERS = {
    "thousand": Decimal("1000"),
    "ribu": Decimal("1000"),
    "rb": Decimal("1000"),
    "mil": Decimal("1000"),
    "тыс": Decimal("1000"),
    "тысяч": Decimal("1000"),
    "тысяча": Decimal("1000"),
    "тысячи": Decimal("1000"),
    "million": Decimal("1000000"),
    "juta": Decimal("1000000"),
    "millones": Decimal("1000000"),
    "millón": Decimal("1000000"),
    "milhao": Decimal("1000000"),
    "milhão": Decimal("1000000"),
    "milhões": Decimal("1000000"),
    "млн": Decimal("1000000"),
    "миллион": Decimal("1000000"),
    "миллиона": Decimal("1000000"),
    "миллионов": Decimal("1000000"),
    "billion": Decimal("1000000000"),
    "miliar": Decimal("1000000000"),
    "млрд": Decimal("1000000000"),
    "миллиард": Decimal("1000000000"),
    "миллиарда": Decimal("1000000000"),
    "миллиардов": Decimal("1000000000"),
}


NUMBER_WORDS = {
    "zero": Decimal("0"),
    "one": Decimal("1"),
    "once": Decimal("1"),
    "single": Decimal("1"),
    "two": Decimal("2"),
    "three": Decimal("3"),
    "four": Decimal("4"),
    "five": Decimal("5"),
    "six": Decimal("6"),
    "seven": Decimal("7"),
    "eight": Decimal("8"),
    "nine": Decimal("9"),
    "ten": Decimal("10"),
    "satu": Decimal("1"),
    "sekali": Decimal("1"),
    "dua": Decimal("2"),
    "tiga": Decimal("3"),
    "empat": Decimal("4"),
    "lima": Decimal("5"),
    "tujuh": Decimal("7"),
    "delapan": Decimal("8"),
    "sembilan": Decimal("9"),
    "sepuluh": Decimal("10"),
    "uno": Decimal("1"),
    "una": Decimal("1"),
    "un": Decimal("1"),
    "dos": Decimal("2"),
    "tres": Decimal("3"),
    "cuatro": Decimal("4"),
    "cinco": Decimal("5"),
    "seis": Decimal("6"),
    "siete": Decimal("7"),
    "ocho": Decimal("8"),
    "nueve": Decimal("9"),
    "diez": Decimal("10"),
    "um": Decimal("1"),
    "uma": Decimal("1"),
    "dois": Decimal("2"),
    "duas": Decimal("2"),
    "quatro": Decimal("4"),
    "sete": Decimal("7"),
    "oito": Decimal("8"),
    "nove": Decimal("9"),
    "dez": Decimal("10"),
}


CJK_ALLOWED_LANGS = {"CN", "ZH", "ZH-CN", "JA", "JP"}


PROCESS_SUFFIXES = {".jsonl", ".log", ".tmp", ".bak", ".manifest"}


SOURCE_HEADERS = {"CN", "ZH", "SOURCE", "TEXT", "原文", "中文", "简体中文", "CN配置"}


SUPPORT_WORKBOOK_NAMES = {"qa摘要.xlsx", "qa_summary.xlsx"}


def source_text(row: dict[str, Any]) -> str:
    return str(row.get("cn") or row.get("CN") or row.get("source") or "")


def protected_tokens(row: dict[str, Any]) -> list[str]:
    tokens = []
    raw_tokens = row.get("tokens") or row.get("protected_tokens") or []
    if isinstance(raw_tokens, str):
        try:
            parsed = json.loads(raw_tokens)
            raw_tokens = parsed if isinstance(parsed, list) else [raw_tokens]
        except json.JSONDecodeError:
            raw_tokens = [raw_tokens]
    if isinstance(raw_tokens, list):
        tokens.extend(str(token) for token in raw_tokens if str(token))
    tokens.extend(token for token in TOKEN_RE.findall(source_text(row)) if is_auto_protected_token(token))
    return sorted(set(tokens), key=len, reverse=True)


def is_auto_protected_token(token: str) -> bool:
    if token.startswith("[") and token.endswith("]"):
        inner = token[1:-1]
        return bool(re.search(r"[\d_:/#=.,-]", inner) or (inner.isupper() and len(inner) <= 12))
    return True


def parse_number_token(token: str) -> Decimal | None:
    raw_with_spaces = token.strip()
    raw = re.sub(r"[ \u00a0\u202f]", "", raw_with_spaces)
    if not raw:
        return None

    if raw.endswith("%"):
        raw = raw[:-1]
        raw_with_spaces = raw_with_spaces[:-1].strip()

    suffix = ""
    word_multiplier: Decimal | None = None
    lowered = raw_with_spaces.lower()
    for word, multiplier in sorted(WORD_MULTIPLIERS.items(), key=lambda item: len(item[0]), reverse=True):
        match = re.search(rf"\s+{re.escape(word)}\.?$", lowered)
        if match:
            word_multiplier = multiplier
            raw = re.sub(r"[ \u00a0\u202f]", "", raw_with_spaces[: match.start()].strip())
            break
    if raw and raw[-1] in "KkMBWw":
        suffix = raw[-1].upper()
        raw = raw[:-1]
    elif raw.endswith(("千", "万", "萬", "亿", "億")):
        suffix = raw[-1]
        raw = raw[:-1]
    if not raw:
        return None

    has_comma = "," in raw
    has_dot = "." in raw
    has_unit = bool(suffix or word_multiplier)
    if has_unit and (has_comma or has_dot):
        if has_comma and has_dot:
            last_comma = raw.rfind(",")
            last_dot = raw.rfind(".")
            last_sep = max(last_comma, last_dot)
            after = raw[last_sep + 1 :]
            before = re.sub(r"[,.]", "", raw[:last_sep])
            raw = before + "." + after
        elif has_comma:
            raw = raw.replace(",", ".")
    elif has_comma or has_dot:
        last_comma = raw.rfind(",")
        last_dot = raw.rfind(".")
        last_sep = max(last_comma, last_dot)
        sep = raw[last_sep]
        after = raw[last_sep + 1 :]
        before = raw[:last_sep]
        thousands_like = len(after) == 3 and all(group.isdigit() for group in re.split(r"[,.]", before) if group)
        if has_comma and has_dot:
            if thousands_like:
                raw = re.sub(r"[,.]", "", raw)
            else:
                raw = re.sub(r"[,.]", "", before) + "." + after
        elif sep == "," and not thousands_like:
            raw = before.replace(",", "") + "." + after
        elif thousands_like:
            raw = re.sub(r"[,.]", "", raw)
        elif sep == ".":
            raw = before.replace(".", "") + "." + after

    try:
        multiplier = word_multiplier or {
            "千": Decimal("1000"),
            "万": Decimal("10000"),
            "萬": Decimal("10000"),
            "亿": Decimal("100000000"),
            "億": Decimal("100000000"),
            "K": Decimal("1000"),
            "M": Decimal("1000000"),
            "B": Decimal("1000000000"),
            "W": Decimal("10000"),
        }.get(suffix, Decimal(1))
        return (Decimal(raw) * multiplier).normalize()
    except InvalidOperation:
        return None


def normalize_spelled_multipliers(text: str) -> str:
    # 数词属于数量单位时先合并，不能把 one million 中的 one 当作独立的 1。
    words = "zero|one|two|three|four|five|six|seven|eight|nine|ten"
    return re.sub(
        rf"\b({words})\s+(thousand|million|billion)\b",
        lambda match: str(int(NUMBER_WORDS[match[1].lower()] * WORD_MULTIPLIERS[match[2].lower()])),
        text,
        flags=re.IGNORECASE,
    )


def numeric_values(text: str) -> set[Decimal]:
    text = normalize_spelled_multipliers(text or "")
    text = re.sub(r"(\d(?:[\d,.]*))(?:<[^>]+>)+\s*([千万萬亿億KkMBWw])", r"\1\2", text)
    word_suffixes = "|".join(re.escape(word) for word in sorted(WORD_MULTIPLIERS, key=len, reverse=True))
    text = re.sub(
        rf"(\d(?:[\d,.]*))(?:<[^>]+>)+\s*({word_suffixes})\b\.?",
        r"\1 \2",
        text,
        flags=re.IGNORECASE,
    )
    text = text.replace("\uff0c", ";")
    values = set()
    for token in NUMBER_RE.findall(text):
        parsed = parse_number_token(token)
        if parsed is not None:
            values.add(parsed)
    lowered = text.lower()
    for word, value in NUMBER_WORDS.items():
        if re.search(rf"\b{re.escape(word)}\b", lowered):
            values.add(value)
    return values


def source_numeric_values(row: dict[str, Any], *, preserve_small: bool = False) -> set[Decimal]:
    src = source_text(row)
    src = re.sub(r"\d+(?:[,.]\d+)?\s*月", "", src)
    src = re.sub(r"(?<=\d)\.(?=\d点)", " ", src)
    # In CN item lists, *10,5分钟 separates quantity 10 from the next item.
    if src.count('*') > 1:
        src = re.sub(r'(\*\d+),(?=\d+(?:分钟|小时|[KkMWw]))', r'\1;', src)
    values = numeric_values(src)
    if CJK_RE.search(src) and not preserve_small:
        values = {
            value
            for value in values
            if not (
                value == value.to_integral_value()
                and Decimal("0") <= value <= Decimal("10")
                and not re.search(rf"(?<!\d){int(value)}\s*%", src)
            )
        }
    reference_en = str(row.get("reference_en") or "")
    for left, right in re.findall(r"(?<!\d)(\d+)\s*[-–—]\s*(\d+)(?!\d)", reference_en):
        joined = Decimal(left + right)
        if joined in values:
            values.discard(joined)
            values.update((Decimal(left), Decimal(right)))
    return values


def numeric_value_present(value: Decimal, targets: set[Decimal]) -> bool:
    if value in targets:
        return True
    if abs(value) >= Decimal("1000"):
        for target in targets:
            if target == 0:
                continue
            if abs(target - value) / abs(value) <= Decimal("0.005"):
                return True
    if Decimal("1") <= value <= Decimal("99"):
        if (Decimal("1900") + value) in targets or (Decimal("2000") + value) in targets:
            return True
    return False


def add_issue(issues: list[dict[str, Any]], issue_type: str, key: str, lang: str, detail: str) -> None:
    issues.append({"severity": "hard", "type": issue_type, "key": key, "lang": lang, "detail": detail})


def _term_hits(row: dict[str, Any]) -> list[dict[str, Any]]:
    raw = row.get("term_hits") or row.get("term_hits_json") or []
    if isinstance(raw, str):
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError:
            return []
        raw = parsed
    if not isinstance(raw, list):
        return []
    return [hit for hit in raw if isinstance(hit, dict)]


def _accepted_term_variants(hit: dict[str, Any], lang: str) -> list[str]:
    values: list[str] = []
    translations = hit.get("translations")
    if isinstance(translations, dict) and translations.get(lang):
        values.append(str(translations[lang]))
    if hit.get(lang):
        values.append(str(hit[lang]))

    variants = hit.get("accepted_variants") or hit.get("variants")
    if isinstance(variants, dict):
        raw = variants.get(lang) or []
    else:
        raw = variants or []
    if isinstance(raw, str):
        values.append(raw)
    elif isinstance(raw, list):
        values.extend(str(value) for value in raw if str(value))

    return sorted({value for value in values if value}, key=len, reverse=True)


def _check_required_terms(issues: list[dict[str, Any]], row: dict[str, Any], key: str, lang: str, target: str) -> None:
    for hit in _term_hits(row):
        if not (hit.get("required") or hit.get("strict")):
            continue
        variants = _accepted_term_variants(hit, lang)
        if variants and not any(variant in target for variant in variants):
            source = hit.get("source") or hit.get("CN") or hit.get("term") or ""
            # 主控语境裁决只豁免这一格的精确源/译文，不能扩成全局代词变体。
            waivers = row.get("term_waivers") or []
            if any(isinstance(waiver, dict)
                   and waiver.get("source") == source and waiver.get("lang") == lang
                   and waiver.get("target") == target
                   and waiver.get("cn") == source_text(row)
                   and waiver.get("translation_source") == row.get("translation_source", row.get("cn", ""))
                   and waiver.get("context") == row.get("context", "")
                   and isinstance(waiver.get("reason"), str) and waiver["reason"].strip()
                   for waiver in waivers):
                continue
            add_issue(issues, "term_missing", key, lang, f"required term not used: {source}")


def pair_integrity_issues(row: dict[str, Any], lang: str, target: str, punctuation_mode: str | None = None) -> list[tuple[str, str]]:
    """Shared source/target checks for cache validation and actual file readback."""
    source = source_text(row)
    issues = list(punctuation_issues(target, lang, punctuation_mode).items())
    if lang.upper() not in CJK_ALLOWED_LANGS and CJK_RE.search(target):
        issues.append(("cjk_residue", "target still contains CJK ideographs"))
    if MOJIBAKE_RE.search(target):
        issues.append(("mojibake", "target contains replacement, null, or repeated question marks"))
    from .semantic_regression import known_semantic_regressions
    issues.extend(("known_semantic_regression", detail) for detail in known_semantic_regressions(row, lang, target))
    tokens = protected_tokens(row)
    for token in tokens:
        required = max(1, source.count(token))
        actual = target.count(token)
        if actual < required:
            issues.append(("protected_token_missing", f"missing protected token {token}: expected {required}, got {actual}"))
        elif actual > required:
            issues.append(("protected_token_extra", f"extra protected token {token}: expected {required}, got {actual}"))
    source_markup = any(re.match(r"</?[A-Za-z]", token) for token in tokens)
    for token in set(TOKEN_RE.findall(target)) - set(tokens):
        if not is_auto_protected_token(token):
            continue
        if token.startswith(("{", "<@", "%", "#")) or (not source_markup and re.match(r"</?[A-Za-z]", token)):
            issues.append(("protected_token_extra", f"unexpected protected token {token}"))
    base_lang = lang.lower().replace('_', '-').split('-')[0]
    source_visible, target_visible = visible_text(source), visible_text(target)
    if base_lang == 'en':
        target_visible = normalize_spelled_multipliers(target_visible)
    target_numbers = numeric_values(target_visible)
    if base_lang in WORDS:
        # Strip cross-language words (PT "dos" is a preposition, ES "dos" is 2).
        target_numbers = {value for token in NUMBER_RE.findall(target_visible) if (value := parse_number_token(token)) is not None}
        words = {**WORDS[base_lang], **({'once': 1, 'twice': 2, 'single': 1} if base_lang == 'en' else {})}
        target_numbers.update(Decimal(value) for word, value in words.items() if re.search(rf'\b{re.escape(word)}\b', target_visible, re.I))
        if re.search(r'每[^，。；\n]{0,16}1\s*(?:次|个|名|辆)', source_visible):
            each = r'\b(?:each|every|per)\b' if base_lang == 'en' else r'\bcada\b'
            if re.search(each, target_visible, re.I): target_numbers.add(Decimal(1))
    source_row = {**row, 'cn': source_visible}
    missing = {value for value in source_numeric_values(source_row, preserve_small=base_lang in WORDS) if not numeric_value_present(value, target_numbers)}
    if missing:
        issues.append(("number_missing", f"missing numeric value(s): {sorted(str(value) for value in missing)}"))
    issues.extend(quantity_issues(source, target, lang))
    issues.extend(semantic_constraint_issues(source, target, lang))
    from .variable_checker import check_bbcode_tags, check_newlines
    issues.extend((issue.check_type, issue.message) for issue in check_bbcode_tags(0, source, target) + check_newlines(0, source, target))
    if source.count('\n') != target.count('\n'):
        issues.append(('newline_mismatch', f"Physical newline count mismatch: source={source.count(chr(10))}, target={target.count(chr(10))}"))
    return list(dict.fromkeys(issues))
