version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      frontend-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "type:maintenance"
      - "area:frontend"
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      backend-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "type:maintenance"
      - "area:backend"
  - package-ecosystem: "pip"
    directory: "/workflow/localization"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      localization-workflow-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "type:maintenance"
      - "area:workflow"
  - package-ecosystem: "pip"
    directory: "/workflow/glossary"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      glossary-workflow-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "type:maintenance"
      - "area:workflow"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "type:maintenance"
      - "ci"
