version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "type:maintenance"
      - "area:frontend"
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "type:maintenance"
      - "area:backend"
  - package-ecosystem: "pip"
    directory: "/workflow/localization"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "type:maintenance"
      - "area:workflow"
  - package-ecosystem: "pip"
    directory: "/workflow/glossary"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "type:maintenance"
      - "area:workflow"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "type:maintenance"
      - "ci"
