"""Generate the product's pure QA rules from the embedded canonical workflow.

No agent runner, CLI, or cross-tree imports are used by the backend at runtime.
Run after workflow synchronization; --check detects unported rule changes.
"""
from __future__ import annotations

import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "workflow/localization/utils"
DEST = ROOT / "backend/app/workflow/large_text_rules"
DEPENDENCIES = (
    "punctuation_policy", "quantity_guard", "review_findings", "semantic_constraints",
    "language_config", "semantic_regression", "variable_checker", "text_normalize",
)
FUNCTIONS = {
    "source_text", "protected_tokens", "is_auto_protected_token", "parse_number_token",
    "normalize_spelled_multipliers", "numeric_values", "source_numeric_values", "numeric_value_present",
    "add_issue", "_term_hits", "_accepted_term_variants", "_check_required_terms", "pair_integrity_issues",
}
NOTICE = "# Generated by scripts/sync_large_text_product_rules.py; do not edit.\n"


def generated_files() -> dict[str, str]:
    files = {"__init__.py": NOTICE}
    for name in DEPENDENCIES:
        text = (SOURCE / f"{name}.py").read_text(encoding="utf-8-sig")
        files[f"{name}.py"] = NOTICE + text.replace("from utils.", "from .")
    text = (SOURCE / "large_text_multilingual_gate.py").read_text(encoding="utf-8-sig")
    nodes = ast.parse(text).body
    selected = []
    found = set()
    for node in nodes:
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            selected.append(ast.get_source_segment(text, node))
        elif isinstance(node, ast.FunctionDef) and node.name in FUNCTIONS:
            found.add(node.name)
            selected.append(ast.get_source_segment(text, node))
    if found != FUNCTIONS:
        raise ValueError(f"Canonical gate API changed: missing {sorted(FUNCTIONS - found)}")
    imports = (
        "from __future__ import annotations\nimport json\nimport re\n"
        "from decimal import Decimal, InvalidOperation\nfrom typing import Any\n"
        "from .punctuation_policy import punctuation_issues\n"
        "from .quantity_guard import quantity_issues, visible_text, WORDS\n"
        "from .semantic_constraints import semantic_constraint_issues\n"
    )
    files["core.py"] = NOTICE + imports + "\n\n" + "\n\n\n".join(selected).replace("from utils.", "from .") + "\n"
    return files


def sync_product_rules(*, check: bool = False) -> int:
    changed = []
    for name, content in generated_files().items():
        path = DEST / name
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        changed.append(name)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    print(f"[product-rules] {'drift' if check else 'updated'}={len(changed)}: {', '.join(changed)}")
    return int(check and bool(changed))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    raise SystemExit(sync_product_rules(check=parser.parse_args().check))
